services:
  - type: web
    name: cleaner-services-website
    env: static
    buildCommand: null
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 